### ISSUE TITLE
Transformation of Markdown files to HTML Help fails

### ISSUE THREAD

**Issue by ritti** [jelovirt/org.lwdita#50] opened 2019-04-23 13:51 UTC
I have a ditamap that contains a DITA file and a Markdown file.

**Environment**: Windows 10, DITA-OT 3.3.1

When I execute the following command 
```cmd
- Chm / htmlhelp Output with dita-ot 3.3.1
"C:\Program Files\DITA-OT\DitaToolKit\dita-ot-3.3.1\bin\dita" --input=Test.ditamap --output=out\htmlhelp --format=htmlhelp --temp=temp\htmlhelp --logfile=loghtmlhelp.xml --clean.temp=no  --verbose --debug
```

the DITA file is shown correctly in the chm file,  but the markdown file cannot be rendered.
See screenshot:

![Testchm](https://user-images.githubusercontent.com/14054526/56585676-9d6fb680-65de-11e9-871f-30c320b9b3c6.png)

When I transform it to pdf or markdown the result is correct
```cmd
- Pdf Output with dita-ot 3.3.1
"C:\Program Files\DITA-OT\DitaToolKit\dita-ot-3.3.1\bin\dita" --input=Test.ditamap --output=out\pdf --format=pdf --temp=temp\pdf --logfile=logpdf.xml --clean.temp=no --verbose --debug

- Markdown_github Output with dita-ot 3.3.3
"C:\Program Files\DITA-OT\DitaToolKit\dita-ot-3.3.1\bin\dita" --input=Test.ditamap --output=out\markdown_github --format=markdown_github --temp=temp\markdown_github --logfile=logmarkdown_github.xml --clean.temp=no --verbose --debug

```

Attached is also the zip file including the test files, the Test.ditamap and all log/temp/output files.

[TestMD2HtmlHelp.zip](https://github.com/jelovirt/org.lwdita/files/3107826/TestMD2HtmlHelp.zip)

Can anyone reproduce this behavior?

**Comment by jelovirt** [comment] 2019-10-04 14:48
Since I don't have Windows, I can't test this. Are you able to convert the content into HTML5 or DITA? If those look ok, then the problem is in DITA-OT HTMLHelp plugin.

**Comment by ritti** [comment] 2019-10-04 18:48
Yes, converting to HTML5 and DITA works correctly.

**Comment by raducoravu** [comment] 2022-03-03 05:45
I can also reproduce the problem with DITA OT 3.7, the problem has probably the same cause as: https://github.com/dita-ot/dita-ot/issues/3839
Switching in DITA OT 3.7 the htmlhelp plugin from "preprocess2" to "preprocess" works for me and properly generates the CHM.

**Comment by jelovirt** [comment] 2022-10-26 16:23
Closing as not related to LwDITA plug-in.

**Closed by jelovirt** 2022-10-26 16:23 UTC
