### ISSUE TITLE
DITA to md breaks with tables containing merged cells

### ISSUE THREAD

**Issue by AnsMelanie** [jelovirt/org.lwdita#191] opened 2023-10-18 09:01 UTC
Below the html code of a table generated from DITA with Oxygen:
```html
<table border="1" class="table">
  <caption/>
  <colgroup>
    <col>
    <col>
    <col>
  </colgroup>
  <tbody class="tbody">
    <tr class="row">
      <td class="entry">
        <strong class="ph b">Keyword</strong>
      </td>
      <td class="entry">
        <strong class="ph b">Data</strong>
      </td>
      <td class="entry">
        <strong class="ph b">Comments</strong>
      </td>
    </tr>
    <tr class="row">
      <td class="entry" colspan="3">
        <strong class="ph b">
          <em class="ph i">Messages periodically sent by the sound generator</em>
        </strong>
      </td>
    </tr>
    <tr class="row">
      <td class="entry">ALIVE</td>
      <td class="entry">none</td>
      <td class="entry">
        <p class="p">Provides information that the sound generator is functioning</p>
        <p class="p">Sent each 500ms, or by a time lapse</p>
        <p class="p">defined by GLOBAL_INIT</p>
      </td>
    </tr>
    <tr class="row">
      <td class="entry" colspan="3">
        <strong class="ph b">
          <em class="ph i">Messages sporadically sent by the sound generator</em>
        </strong>
      </td>
    </tr>
    <tr class="row">
      <td class="entry">WARNING</td>
      <td class="entry">string</td>
      <td class="entry">Reports a warning</td>
    </tr>
    <tr class="row">
      <td class="entry">ERROR</td>
      <td class="entry">string</td>
      <td class="entry">Reports an error</td>
    </tr>
    <tr class="row">
      <td class="entry">INFO END_PLAY_3D</td>
      <td class="entry">Id (int)</td>
      <td class="entry">
        <p class="p">Informs that the playback of the 3D</p>
        <p class="p">sound associated with Id is over</p>
      </td>
    </tr>
    <tr class="row">
      <td class="entry">INFO END_PLAY_AMBIANCE</td>
      <td class="entry">Id (int)</td>
      <td class="entry">
        <p class="p">Informs that the playback of the</p>
        <p class="p">ambiance sound associated with Id is over</p>
      </td>
    </tr>
  </tbody>
</table>
```

If converted from DITA to md with Oxygen, the result is broken as follows:
```markdown
|**Keyword**|**Data**|**Comments**|
|***Messages periodically sent by the sound generator***|
|ALIVE|none|Provides information that the sound generator is functioning

 Sent each 500ms, or by a time lapse

 defined by GLOBAL\_INIT

|
|***Messages sporadically sent by the sound generator***|
|WARNING|string|Reports a warning|
|ERROR|string|Reports an error|
|INFO END\_PLAY\_3D|Id \(int\)|Informs that the playback of the 3D

 sound associated with Id is over

|
|INFO END\_PLAY\_AMBIANCE|Id \(int\)|Informs that the playback of the

 ambiance sound associated with Id is over

|
```

**Comment by raducoravu** [comment] 2023-10-18 09:13
@AnsMelanie I edited your content a bit to show more exactly the blocks of code.

**Comment by raducoravu** [comment] 2023-10-18 09:14
This issue si similar with #76 there are table entries with multiple block level elements (paragraphs in this case) inside them.

**Comment by jelovirt** [comment] 2023-11-02 14:11
Closing as duplicate of #76

**Closed by jelovirt** 2023-11-02 14:11 UTC
